# Generated by Django 4.1.7 on 2023-04-14 23:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uid',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('vendor', 'uid')},
        ),
    ]
