# Generated by Django 4.1.7 on 2023-04-15 00:22

import datetime
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('brand', models.CharField(max_length=50, verbose_name='')),
                ('available', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('uid', models.CharField(max_length=255)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Amazon', 'Amazon'), ('Jumia', 'Jumia'), ('Noon', 'Noon')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('operating_system', models.CharField(blank=True, max_length=50, null=True)),
                ('wifi', models.CharField(blank=True, max_length=50, null=True)),
                ('bluetooth', models.CharField(blank=True, max_length=50, null=True)),
                ('usb', models.CharField(blank=True, max_length=50, null=True)),
                ('hdmi', models.BooleanField(default=True)),
                ('display_type', models.CharField(blank=True, max_length=50, null=True)),
                ('display_size', models.CharField(blank=True, max_length=50, null=True)),
                ('display_resolution', models.CharField(blank=True, max_length=50, null=True)),
                ('refresh_rate', models.IntegerField(blank=True, null=True)),
                ('gpu_brand', models.CharField(max_length=100)),
                ('gpu_model', models.CharField(max_length=100)),
                ('gpu_memory', models.PositiveSmallIntegerField(help_text='The amount of memory on the GPU in GB')),
                ('gpu_cuda_cores', models.PositiveSmallIntegerField(blank=True, help_text='The number of CUDA cores on the GPU (for NVIDIA GPUs)', null=True)),
                ('sound', models.CharField(blank=True, max_length=50, null=True)),
                ('smart_tv', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tablet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('operating_system', models.CharField(blank=True, max_length=50, null=True)),
                ('wifi', models.CharField(blank=True, max_length=50, null=True)),
                ('bluetooth', models.CharField(blank=True, max_length=50, null=True)),
                ('usb', models.CharField(blank=True, max_length=50, null=True)),
                ('display_type', models.CharField(blank=True, max_length=50, null=True)),
                ('display_size', models.CharField(blank=True, max_length=50, null=True)),
                ('display_resolution', models.CharField(blank=True, max_length=50, null=True)),
                ('refresh_rate', models.IntegerField(blank=True, null=True)),
                ('cpu_brand', models.CharField(max_length=100)),
                ('cpu_series', models.CharField(max_length=100)),
                ('cpu_num_cores', models.PositiveSmallIntegerField()),
                ('cpu_num_threads', models.PositiveSmallIntegerField()),
                ('cpu_cache_memory', models.CharField(max_length=100)),
                ('gpu_brand', models.CharField(max_length=100)),
                ('gpu_model', models.CharField(max_length=100)),
                ('gpu_memory', models.PositiveSmallIntegerField(help_text='The amount of memory on the GPU in GB')),
                ('gpu_cuda_cores', models.PositiveSmallIntegerField(blank=True, help_text='The number of CUDA cores on the GPU (for NVIDIA GPUs)', null=True)),
                ('battery_capacity', models.CharField(max_length=50)),
                ('battery_life', models.CharField(max_length=50)),
                ('storage', models.PositiveSmallIntegerField()),
                ('storage_type', models.CharField(max_length=50)),
                ('ram', models.PositiveSmallIntegerField()),
                ('ram_type', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='product',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.vendor'),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateField(default=datetime.date.today)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='product.product')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('operating_system', models.CharField(blank=True, max_length=50, null=True)),
                ('wifi', models.CharField(blank=True, max_length=50, null=True)),
                ('bluetooth', models.CharField(blank=True, max_length=50, null=True)),
                ('usb', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_camera_resolution', models.CharField(blank=True, max_length=50, null=True)),
                ('front_camera_resolution', models.CharField(blank=True, max_length=50, null=True)),
                ('display_type', models.CharField(blank=True, max_length=50, null=True)),
                ('display_size', models.CharField(blank=True, max_length=50, null=True)),
                ('display_resolution', models.CharField(blank=True, max_length=50, null=True)),
                ('refresh_rate', models.IntegerField(blank=True, null=True)),
                ('cpu_brand', models.CharField(max_length=100)),
                ('cpu_series', models.CharField(max_length=100)),
                ('cpu_num_cores', models.PositiveSmallIntegerField()),
                ('cpu_num_threads', models.PositiveSmallIntegerField()),
                ('cpu_cache_memory', models.CharField(max_length=100)),
                ('gpu_brand', models.CharField(max_length=100)),
                ('gpu_model', models.CharField(max_length=100)),
                ('gpu_memory', models.PositiveSmallIntegerField(help_text='The amount of memory on the GPU in GB')),
                ('gpu_cuda_cores', models.PositiveSmallIntegerField(blank=True, help_text='The number of CUDA cores on the GPU (for NVIDIA GPUs)', null=True)),
                ('battery_capacity', models.CharField(max_length=50)),
                ('battery_life', models.CharField(max_length=50)),
                ('storage', models.PositiveSmallIntegerField()),
                ('storage_type', models.CharField(max_length=50)),
                ('ram', models.PositiveSmallIntegerField()),
                ('ram_type', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('operating_system', models.CharField(blank=True, max_length=50, null=True)),
                ('wifi', models.CharField(blank=True, max_length=50, null=True)),
                ('bluetooth', models.CharField(blank=True, max_length=50, null=True)),
                ('usb', models.CharField(blank=True, max_length=50, null=True)),
                ('hdmi', models.BooleanField(default=True)),
                ('display_type', models.CharField(blank=True, max_length=50, null=True)),
                ('display_size', models.CharField(blank=True, max_length=50, null=True)),
                ('display_resolution', models.CharField(blank=True, max_length=50, null=True)),
                ('refresh_rate', models.IntegerField(blank=True, null=True)),
                ('cpu_brand', models.CharField(max_length=100)),
                ('cpu_series', models.CharField(max_length=100)),
                ('cpu_num_cores', models.PositiveSmallIntegerField()),
                ('cpu_num_threads', models.PositiveSmallIntegerField()),
                ('cpu_cache_memory', models.CharField(max_length=100)),
                ('gpu_brand', models.CharField(max_length=100)),
                ('gpu_model', models.CharField(max_length=100)),
                ('gpu_memory', models.PositiveSmallIntegerField(help_text='The amount of memory on the GPU in GB')),
                ('gpu_cuda_cores', models.PositiveSmallIntegerField(blank=True, help_text='The number of CUDA cores on the GPU (for NVIDIA GPUs)', null=True)),
                ('battery_capacity', models.CharField(max_length=50)),
                ('battery_life', models.CharField(max_length=50)),
                ('storage', models.PositiveSmallIntegerField()),
                ('storage_type', models.CharField(max_length=50)),
                ('ram', models.PositiveSmallIntegerField()),
                ('ram_type', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('alt', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='product_pro_search__e78047_gin'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('vendor', 'uid')},
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('product', 'order')},
        ),
    ]
