# Generated by Django 4.1.7 on 2023-05-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='cpu_cache_memory',
        ),
        migrations.AlterField(
            model_name='laptop',
            name='cpu_num_cores',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='gpu_memory',
            field=models.CharField(help_text='The amount of memory on the GPU in GB', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='storage_type',
            field=models.CharField(default='HDD', max_length=50, null=True),
        ),
    ]
