# Generated by Django 4.1.7 on 2023-04-30 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-views', '-rating']},
        ),
    ]
