# Generated by Django 4.1.7 on 2023-05-12 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_laptop_product_alter_mobile_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptop',
            old_name='model',
            new_name='_model',
        ),
        migrations.RenameField(
            model_name='mobile',
            old_name='model',
            new_name='_model',
        ),
        migrations.RenameField(
            model_name='tablet',
            old_name='model',
            new_name='_model',
        ),
        migrations.RenameField(
            model_name='tv',
            old_name='model',
            new_name='_model',
        ),
    ]
