# Generated by Django 4.1.7 on 2023-05-13 19:41

from django.db import migrations, models
import product.models.category


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=product.models.category.categor_image_path),
        ),
    ]
