# Generated by Django 4.1.7 on 2023-05-12 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_model_laptop__model_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laptop',
            old_name='_model',
            new_name='model_name',
        ),
        migrations.RenameField(
            model_name='mobile',
            old_name='_model',
            new_name='model_name',
        ),
        migrations.RenameField(
            model_name='tablet',
            old_name='_model',
            new_name='model_name',
        ),
        migrations.RenameField(
            model_name='tv',
            old_name='_model',
            new_name='model_name',
        ),
    ]
