# Generated by Django 4.1.7 on 2023-06-19 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_laptop_product_alter_mobile_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['date']},
        ),
    ]
