# Generated by Django 4.1.7 on 2023-05-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_laptop_ram_alter_laptop_storage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='operating_system',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='operating_system',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='operating_system',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
