# Generated by Django 4.1.7 on 2023-05-06 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_laptop_product_alter_mobile_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobile',
            old_name='bluetooth',
            new_name='connectivity_tech',
        ),
        migrations.RenameField(
            model_name='tablet',
            old_name='bluetooth',
            new_name='connectivity_tech',
        ),
        migrations.RenameField(
            model_name='tv',
            old_name='bluetooth',
            new_name='connectivity_tech',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='bluetooth',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='cpu_num_threads',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='cpu_series',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='gpu_cuda_cores',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='gpu_model',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='hdmi',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='usb',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='wifi',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='cpu_brand',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='cpu_cache_memory',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='cpu_num_cores',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='cpu_num_threads',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='cpu_series',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='front_camera_resolution',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='gpu_brand',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='gpu_cuda_cores',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='gpu_memory',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='gpu_model',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='primary_camera_resolution',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='ram_type',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='storage_type',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='usb',
        ),
        migrations.RemoveField(
            model_name='mobile',
            name='wifi',
        ),
        migrations.RemoveField(
            model_name='tablet',
            name='cpu_brand',
        ),
        migrations.RemoveField(
            model_name='tablet',
            name='cpu_cache_memory',
        ),
        migrations.RemoveField(
            model_name='tablet',
            name='cpu_num_cores',
        ),
        migrations.RemoveField(
            model_name='tablet',
            name='cpu_num_threads',
        ),
        migrations.RemoveField(
            model_name='tablet',
            name='cpu_series',
        ),
        migrations.RemoveField(
            model_name='tablet',
            name='gpu_brand',
        ),
        migrations.RemoveField(
            model_name='tablet',
            name='gpu_cuda_cores',
        ),
        migrations.RemoveField(
            model_name='tablet',
            name='gpu_memory',
        ),
        migrations.RemoveField(
            model_name='tablet',
            name='gpu_model',
        ),
        migrations.RemoveField(
            model_name='tablet',
            name='ram_type',
        ),
        migrations.RemoveField(
            model_name='tablet',
            name='storage_type',
        ),
        migrations.RemoveField(
            model_name='tablet',
            name='usb',
        ),
        migrations.RemoveField(
            model_name='tablet',
            name='wifi',
        ),
        migrations.RemoveField(
            model_name='tv',
            name='gpu_brand',
        ),
        migrations.RemoveField(
            model_name='tv',
            name='gpu_cuda_cores',
        ),
        migrations.RemoveField(
            model_name='tv',
            name='gpu_memory',
        ),
        migrations.RemoveField(
            model_name='tv',
            name='gpu_model',
        ),
        migrations.RemoveField(
            model_name='tv',
            name='hdmi',
        ),
        migrations.RemoveField(
            model_name='tv',
            name='operating_system',
        ),
        migrations.RemoveField(
            model_name='tv',
            name='sound',
        ),
        migrations.RemoveField(
            model_name='tv',
            name='usb',
        ),
        migrations.RemoveField(
            model_name='tv',
            name='wifi',
        ),
        migrations.AddField(
            model_name='laptop',
            name='cpu_speed',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='cpu_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='laptop',
            name='gpu_coprocessor',
            field=models.CharField(help_text='The model of a specific type (e.g AMD Radeon Graphics, ..)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='battery_capacity',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='battery_life',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='cpu_brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='cpu_cache_memory',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='cpu_num_cores',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='gpu_brand',
            field=models.CharField(help_text='The type of GPU chip (e.g. NVIDIA, AMD)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='gpu_memory',
            field=models.PositiveSmallIntegerField(help_text='The amount of memory on the GPU in GB', null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ram',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ram_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='storage',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='storage_type',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='battery_capacity',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='battery_life',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='ram',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='storage',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='battery_capacity',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='battery_life',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='ram',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='storage',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tv',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AlterField(
            model_name='tv',
            name='smart_tv',
            field=models.BooleanField(default=True),
        ),
    ]
