# Generated by Django 4.1.7 on 2023-05-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_rename_bluetooth_mobile_connectivity_tech_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='refresh_rate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='refresh_rate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='refresh_rate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='tv',
            name='refresh_rate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
