# Generated by Django 4.1.7 on 2023-05-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_product_brand_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='model',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='model',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tablet',
            name='model',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tv',
            name='model',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
