# Generated by Django 4.1.7 on 2023-05-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_laptop_model_alter_mobile_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='alt',
        ),
        migrations.AlterField(
            model_name='image',
            name='image_url',
            field=models.CharField(max_length=50),
        ),
    ]
