# Generated by Django 4.1.7 on 2023-06-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='desired_price_reached',
            new_name='notify',
        ),
        migrations.AddField(
            model_name='favorite',
            name='last_notified_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='favorite',
            name='notify_when_any_drop',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='desired_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
