# Generated by Django 4.1.7 on 2023-06-19 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favorite', '0003_rename_desired_price_reached_favorite_notify_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='notify',
            new_name='price_change_notified',
        ),
    ]
