# Generated by Django 4.1.7 on 2023-04-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourite', '0001_initial'),
        ('product', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourties',
            field=models.ManyToManyField(related_name='users', through='favourite.Favourite', to='product.product'),
        ),
    ]
