# Generated by Django 4.1.7 on 2023-04-22 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active',
        ),
    ]
